apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jbocd54dg-python 
  janus-idp.io/tekton: jbocd54dg-python
  backstage.io/kubernetes-id: jbocd54dg-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jbocd54dg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml